# Generated by Django 6.0.3 on 2026-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('itinerary', models.TextField()),
                ('hero_image', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
