# Generated by Django 6.0.3 on 2026-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(choices=[('agra', 'Agra'), ('delhi', 'Delhi'), ('jaipur', 'Jaipur')], default='agra', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hero_image',
            field=models.ImageField(upload_to='tours/'),
        ),
    ]
