# Generated by Django 6.0.3 on 2026-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='You can write the full blog article here.'),
        ),
    ]
